[project]
name = "plan-to-action"
version = "0.1.0"
description = "Converts abstract human instructions into executable function calls using a local LLM planner pipeline."
authors = [
    {name = "Shrey Gajjar", email = "shreydotgajjar@gmail.com"}
]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.9"
dependencies = [
    "langchain-ollama",
    "langchain",
    "torch",
    "transformers",
    "python-dotenv",
    "typer",
    "questionary",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"